### ISSUE TITLE
CI/CD: need a DEV .env.secret file for github actions to run integration tests

### ISSUE THREAD

**Issue by JudeDavis1** [j-koziel/cong-manager#47]
Find a way to set environment variables in the integration/e2e test workflow for GitHub actions. These will contain sample secrets.

Research: to set private keys etc., find a way to store a .env.secret or the like. So that we can do e2e tests.

For integration tests, we could (whenever we use API keys, secrets, etc.) mock external API requests. E2E tests may need the actual keys. TBD.

**Comment by j-koziel** [comment]
I'm pretty sure you can create repository secrets and just access those from the workflow file like this: {{SECRET_VAR}}
